spring:
    datasource:
        url: jdbc:postgresql://test-database.cdq24ie048jx.ap-south-1.rds.amazonaws.com:5432/reels_music
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

aws:
    s3:
        bucket: ${S3_BUCKET:reels-music-bucket}
        region: ${S3_REGION:ap-south-1}